### PR TITLE
drop asf-tools env from container and watermap hyp3 entrypoint

### PR DESCRIPTION
**Pull request by jhkennedy**
Once HyP3 uses asf-tools directly to run the water map and flood depth code, we can drop all that from this container. 

Will need to test that RTC and InSAR jobs still work.

### CODE REVIEW

**Comment by forrestfwilliams** [comment]
@jhkennedy The changes here look good, nothing other than the portions pertaining to `asf-tools` has been dropped. I'd like to try rebuilding the container locally and running InSAR/RTC jobs before giving the thumbs-up however. I'll likely get to this Monday morning.

**Comment by jhkennedy** [comment]
@forrestfwilliams you can also merge and try it in test if you like. Guess it'll need a changelog first

**Comment by forrestfwilliams** [comment]
That works for me. If you add a changelog entry, I'll approve.

**Comment by jhkennedy** [comment]
@forrestfwilliams done!

**Review by forrestfwilliams — APPROVED** [review]
LGTM!

**Pull request merged**
