### PR TITLE
use geopandas to subset shapefile prior to creating water mask

### PR DESCRIPTION
**Pull request by asjohnston-asf**

### CODE REVIEW

**Review by cirrusasf — APPROVED** [review]
looks good to  me.

**Comment by asjohnston-asf** [comment]
I was able to successfully run `create_water_mask` and get reasonable output for the six InSAR products I tested last week (including the two that previously failed).

However, I'm now getting this traceback for both `++process insar` and `++process rtc`, likely a version conflict introduced by adding `geopandas` to setup.py:
```
$ docker run -it -v $(pwd):/home/conda 845172464411.dkr.ecr.us-west-2.amazonaws.com/hyp3-gamma:4.6.2.dev43_g6615ada ++process insar
Traceback (most recent call last):
  File "/usr/local/bin/hyp3_gamma", line 5, in <module>
    from hyp3_gamma.__main__ import main
  File "/usr/local/lib/python3.6/dist-packages/hyp3_gamma/__main__.py", line 19, in <module>
    from hyp3_gamma.rtc.rtc_sentinel import rtc_sentinel_gamma
  File "/usr/local/lib/python3.6/dist-packages/hyp3_gamma/rtc/rtc_sentinel.py", line 29, in <module>
    from hyp3lib.raster_boundary2shape import raster_boundary2shape
  File "/usr/local/lib/python3.6/dist-packages/hyp3lib/raster_boundary2shape.py", line 9, in <module>
    from hyp3lib.asf_time_series import raster_metadata
  File "/usr/local/lib/python3.6/dist-packages/hyp3lib/asf_time_series.py", line 6, in <module>
    import statsmodels.api as sm
  File "/usr/local/lib/python3.6/dist-packages/statsmodels/api.py", line 5, in <module>
    from . import regression
  File "/usr/local/lib/python3.6/dist-packages/statsmodels/regression/__init__.py", line 1, in <module>
    from .linear_model import yule_walker
  File "/usr/local/lib/python3.6/dist-packages/statsmodels/regression/linear_model.py", line 40, in <module>
    from scipy import stats
  File "/usr/lib/python3/dist-packages/scipy/stats/__init__.py", line 348, in <module>
    from .stats import *
  File "/usr/lib/python3/dist-packages/scipy/stats/stats.py", line 177, in <module>
    from . import distributions
  File "/usr/lib/python3/dist-packages/scipy/stats/distributions.py", line 13, in <module>
    from . import _continuous_distns
  File "/usr/lib/python3/dist-packages/scipy/stats/_continuous_distns.py", line 15, in <module>
    from scipy._lib._numpy_compat import broadcast_to
  File "/usr/lib/python3/dist-packages/scipy/_lib/_numpy_compat.py", line 10, in <module>
    from numpy.testing.nosetester import import_nose
ModuleNotFoundError: No module named 'numpy.testing.nosetester'
```

**Comment by asjohnston-asf** [comment]
Our subsetting of the shapefile might also fail for InSAR products crossing the antimeridian, we should test one of those prior to merging.

**Comment by asjohnston-asf** [comment]
Confirmed that `numpy.testing.nosetester` was deprecated in numpy `1.18.0`. Removing the `statsmodels==0.9.0` install from the Dockerfile resolved the import error in the docker environment. In our entire code base `statsmodels` is only referenced in `hyp3_lib.asf_time_series.time_series_slice`, which is imported but never used by any of our plugin code. I've run a single RTC job and a single InSAR job; both finished successfully and the geotiffs pass a quick visual inspection.

https://github.com/ASFHyP3/hyp3-lib/blob/d108842345ae0c2be8078a9b6cc04bbabe9a4dee/hyp3lib/asf_time_series.py#L368

**Review by jhkennedy — APPROVED** [review]

**Pull request merged**
